version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-backend
    ports:
      - "9002:3000"
    env_file:
      - .env
    restart: always
